# prometheus-additional.yaml

# Prometheus scrape configuration
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['98.80.10.238:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Change this based on your needs
    static_configs:
      - targets:
        - http://98.80.10.238/events  # Ensure this is the correct URL to probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: bb-exporter-prometheus-blackbox-exporter.monitoring:9115  # Assuming Blackbox Exporter service name in Kubernetes
                     

